### ISSUE TITLE
Release 4.0.40

### ISSUE THREAD

**Issue by DavidAntonin** [BJReplay/ha-solcast-solar#104]
Can you please release 4.0.40? My HA is still on 4.0.31
Thank you

**Comment by autoSteve** [comment]
We'd love to, and It'll come, but please be patient.

The next non-beta release will probably be as v4.1.0.

The HACS PR https://github.com/hacs/default/pull/2535 is all approved, but awaiting merge by a repo owner. We're holding off publishing anything as 'latest' until that happens, as that HACS PR would require modification were we to release a latest beyond v4.0.31. Additionally, further development beyond bug fixes has been happening, and we'd really like to get these 100% right before the next 'latest'. Things like additional attributes, configuration options for those attributes, and spline interpolations for inter-half hour values. I think these are great additions.

In the meantime, just turn on `Show beta versions` when redownloading in HACS to get the latest code. Come join us testing the betas and join in the pre-release discussions. We'd love to hear your experiences, and the more testers the better.

v4.0.31 carries very few faults. But it does carry some. Give the batas a go! v4.0.40 is at 161 downloads with much issue silence.

v4.0.41 will probably release within hours, which fixes current outstanding issues and adds some further interpolation goodness.

**Comment by autoSteve** [comment]
FYI @DavidAntonin, v4.0.41 pre-release is up and discussion started.

**Comment by autoSteve** [comment]
Okay. I was wrong @DavidAntonin. #willfix... Thanks @BJReplay for making the call. HACS are dragging their feet with integration adds until their v2.0, so we will not wait.

v4.1.0 has been released as latest.
