### ISSUE TITLE
Forecast Next 2 Hours doesn't work anymore

### ISSUE THREAD

**Issue by brugk000** [BJReplay/ha-solcast-solar#121]
### The problem

I configured a sensor with the forecast for the next 2 hours.
This doesn't work anymore with the new version 4.1.0

### What version of Solcast Integration has the issue?

V4.1.0

### What version of Home Assistant are you using?

2024.7.4

### Diagnostics information

none

### Logs debug/info/error output

```txt
none
```

**Comment by autoSteve** [comment]
What doesn't work? I've got one configured for eight hours and it's fine.

The sensor name has been renamed, so is this behind something "doesn't work anymore"?

Without further detail beyond your one-line 'don't work' I can only make guesses.

**Comment by brugk000** [comment]
Sorry for the mistake. Good you mentioned the change in sensor name.
Didn't found that in de changelog
Thanks

**Comment by autoSteve** [comment]
<img width="999" alt="image" src="https://github.com/user-attachments/assets/fabf4f3c-a9c0-44c7-b4e1-066e1f67bf9f">
