### ISSUE TITLE
Weird attribute names

### ISSUE THREAD

**Issue by home409ca** [BJReplay/ha-solcast-solar#137]
Solcast PV Forecast v 4.1.3
What are these attributes? In previous versions they were described, but here I see strange numbers...
![image](https://github.com/user-attachments/assets/d6237920-ca5c-4464-9b22-a1ea564f84d6)

**Comment by autoSteve** [comment]
These are a breakdown of Solcast sites. The 'strange numbers' are your rooftop site IDs.

If you don't want them, then turn them off in the integration configuration. There are options to do so to reduce clutter.

**Comment by autoSteve** [comment]
(If the translations to do so are inadequate do please call this out. Polish is not one of my languages.)

**Comment by home409ca** [comment]
I created a translation, restarted HA but I still have the same...
![image](https://github.com/user-attachments/assets/b676c429-bf3d-4b47-9b88-b7100d4e9167)

[pl.json](https://github.com/user-attachments/files/16636788/pl.json)

**Comment by autoSteve** [comment]
I absolutely do not understand, @home409ca, but thanks for the translation.

The attributes are selectable when you configure the integration. Turn them off. Turn them on. The integration does not care. It will present attributes that are selected.

Atrybuty można wybrać podczas konfigurowania integracji. Wyłącz je. Włącz je. Ustawienie integracji nie ma znaczenia.  Pokaże wybrane atrybuty.

**Comment by autoSteve** [comment]
Go to ustawienia | urządzeń i usług | Solcast PV Forecast | KONFIGURUJ, then select atrybuty, then turn off those you do not need... Wszystko zostanie rozwiązane.

**Comment by autoSteve** [comment]
(I am quite new to Polish. Forgive...)

**Comment by home409ca** [comment]
I removed the HACS integration. I downloaded it again. I reinstalled and configured it again and I still see the Resource ID instead of the patch name.

![image](https://github.com/user-attachments/assets/dc979f80-f138-42b1-a9dd-ae9050230f31)

I am also sending the language file again, there was one error.

[pl.json](https://github.com/user-attachments/files/16640358/pl.json)
