### ISSUE TITLE
hacs.json name property to match manifest.json?

### ISSUE THREAD

**Issue by davidrapan** [BJReplay/ha-solcast-solar#140]
What about to change (from hacs.json):
```
"name": "Solcast PV Solar"
```
to (which is in manifest.json):
```
"name": "Solcast PV Forecast"
```
So is the naming the same?

_Also "PV Solar" is somewhat redundant term, imo._ 😋

But I don't want to be pedantic or anything like that. 😆 

Keep up and have fun guys!

**Comment by autoSteve** [comment]
As a fellow pedant, in principle I agree, but for the wider implications regarding an outstanding HACS PR I will defer to @BJReplay. (Assuming that PR is ever to be merged, given HACS.next...)

**Comment by BJReplay** [comment]
Yeah, not a bad tidy up, provided a) it doesn't break anything, including nearly 4,000 HACS installs, and b) the PR, though that's probably of secondary importance.

**Comment by davidrapan** [comment]
> As a fellow pedant

🤝

> Assuming that PR is ever to be merged, given HACS.next...

I'm wondering could you tell me more about that? As I too have PR there for [davidrapan/ha-solarman](https://github.com/davidrapan/ha-solarman)

> a) it doesn't break anything, including nearly 4,000 HACS installs

I was assuming that it's only display related thing and the crucial parts are repo and folder name, hm?

**Comment by autoSteve** [comment]
> I'm wondering could you tell me more about that? As I have PR there too...

It looks highly likely that there's not going to be any more repos added to HACS current before HACS v2, which is coming sometime maybe. There are many PRs outstanding, some waiting for six months with much chirping crickets, despite being approved for merge as we are. The HACS Discord channel apparently has more.

**Comment by BJReplay** [comment]
> I was assuming that it's only display related thing and the crucial parts are repo and folder name, hm?

That's my assumption, but I don't know enough to be sure.

I'd test this change in a pre-release just in case.  Having assumed something about updating the readme which demonstrated two things (one, with the benefit of hindsight, obvious, the other, not so much) I'm wary.

**Comment by BJReplay** [comment]
> Also "PV Solar" is somewhat redundant term, imo

What, no thermal solar for you?  At this time of year, most of my heating is thermal solar, thank you very much 🤣.

Yes, agreed.

I think we'll include it in the next release as a beta, just in case.  I'll add it to the open PR, we'll release as a pre-release, and if OK, upgrade to latest release.
