### ISSUE TITLE
Adding a second API key resets usage for the existing key

### ISSUE THREAD

**Issue by autoSteve** [BJReplay/ha-solcast-solar#154]
When the integration is configured with a single API key, and then at a later date a second API key is added then site usage will be reset to zero.

This has been introduced with the removal by Solcast of the API call to get usage/total for each API key.

Nothing will break, but this may be annoying.

**Comment by BJReplay** [comment]
This appears to be reproducible with a single API key, and with adding a second resource ID to the API Key.

I did this by adding a second micro array (1kW AC/DC) at the same location as my existing array).

This is the partially redacted content of solcast-sites.json at the time that the integration is failing to load:

`{"sites": [{"name": "BLAH", "resource_id": "3f77-9366-ebbc-b925", "capacity": 5, "capacity_dc": 4.85, "longitude": yada, "latitude": yada, "azimuth": -123, "tilt": 5, "install_date": "2012-04-18T14:00:00.0000000Z", "tags": ["Home ", "yada", "Flat Roof"]}, {"name": "BLAH 2.0", "resource_id": "3173-8af2-5d85-fae4", "capacity": 1, "capacity_dc": 1, "longitude": yada, "latitude": yada, "azimuth": 123, "tilt": 5, "install_date": "2001-12-31T13:00:00.0000000Z", "tags": ["Test"], "location": "yada, VIC Australia"}], "page_count": 1, "current_page": 1, "total_records": 2}`

Note that the first resource_id was the existing one, and the second resource_id was the newly added resource_id.
