### ISSUE TITLE
Random corruption of solcast.json

### ISSUE THREAD

**Issue by BJReplay** [BJReplay/ha-solcast-solar#155]
I went down the rabbit hole and wanted to see if i could find a pattern.
One thing i did find was a single case, around the time history data dissapeared, where solcast.json was literally just this:

```
{"siteinfo": {"xxxx-xxxx-xxxx-xxxx": {"forecasts": [] "tally": 0}}, "last_updated": "xxxx", "version": 4}
```

Probably some issue thats already been addressed, but i did notice that history dissapeared occasionally. One thing I didnt know, until this evening, was that it wasnt meant to!

_Originally posted by @sh00t2kill in https://github.com/BJReplay/ha-solcast-solar/issues/153#issuecomment-2324678104_

**Comment by autoSteve** [comment]
At present, my thoughts are that this bug is squashed. Changes to serialisation. Changes to startup. Changes to exception handling. This issue would need to sit for a long time stale until this is proven in the current code.

**Comment by BJReplay** [comment]
Will close.
