### ISSUE TITLE
instrumentation bug

### ISSUE THREAD

**Issue by BJReplay** [BJReplay/ha-solcast-solar#197]
Despite providing very little information @matomatusov, I think I have an answer for you.

<img width="305" alt="image" src="https://github.com/user-attachments/assets/9c3aa778-b938-4b3b-9e58-2787c9d6dfb2">

Note in my diagnostic usage the value says 8. This is wrong. I have used two API calls in this UTC day period, and the logged forecast fetches reflect this. Now open the diagnostic sensor. I expect you will see something like this. The history shows correctly, yet the API used does not.

<img width="556" alt="image" src="https://github.com/user-attachments/assets/18662606-3ada-492e-8c55-d99e9f78add8">

So this is an instrumentation bug, and thanks for pointing it out. It will be fixed in a future version.

_Originally posted by @autoSteve in https://github.com/BJReplay/ha-solcast-solar/issues/187#issuecomment-2424468689_

**Comment by gcoan** [comment]
> I just wonder why the entire API limit was not reached.

Have a look in your HA log.  I suspect you (like many of the rest of us) have been suffering from 429 errors from Solcast that mean that some of the scheduled retrievals have been attempted but are not successful.

**Comment by matomatusov** [comment]
> Have a look in your HA log. I suspect you (like many of the rest of us) have been suffering from 429 errors from Solcast that mean that some of the scheduled retrievals have been attempted but are not successful.

HA log -  Setting - System - Logs  - I only have this warning

Logger: homeassistant.components.sensor.recorder
Source: components/sensor/recorder.py:254
integration: Sensor (documentation, issues)
First occurred: 6:26:15 PM (7 occurrences)
Last logged: 6:26:15 PM

The unit of sensor.solcast_pv_forecast_day_3 (None) cannot be converted to the unit of previously compiled statistics (kWh). Generation of long term statistics will be suppressed unless the unit changes back to kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.solcast_pv_forecast_day_4 (None) cannot be converted to the unit of previously compiled statistics (kWh). Generation of long term statistics will be suppressed unless the unit changes back to kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.solcast_pv_forecast_day_5 (None) cannot be converted to the unit of previously compiled statistics (kWh). Generation of long term statistics will be suppressed unless the unit changes back to kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.solcast_pv_forecast_day_6 (None) cannot be converted to the unit of previously compiled statistics (kWh). Generation of long term statistics will be suppressed unless the unit changes back to kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this
The unit of sensor.solcast_pv_forecast_day_7 (None) cannot be converted to the unit of previously compiled statistics (kWh). Generation of long term statistics will be suppressed unless the unit changes back to kWh or a compatible unit. Go to https://my.home-assistant.io/redirect/developer_statistics to fix this

**Comment by autoSteve** [comment]
> I only have this warning

Repair the issues. You don't care about statistics for future forecasts. (This may be related to change that @gcoan requested to change the state_slass of these sensors.

**Comment by autoSteve** [comment]
> I just wonder why the entire API limit was not reached

@matomatusov check your logs for _successful_ fetches. Count them. If you cannot see them then enable INFO level logging for the integration. (Follow this https://github.com/BJReplay/ha-solcast-solar/discussions/38#discussioncomment-9792389, but set for info, not debug.)

There is an instrumentation issue, after all.

**Comment by gcoan** [comment]
> Repair the issues. You don't care about statistics for future forecasts. (This may be related to change that @gcoan requested to change the state_slass of these sensors.

I'll get forever tarred with any statistics issues now...

On mine, 4.2.0, I have statistics happily collating for all the pv_today/tomorrow/d3 etc, uom=kWh for all.

Whether I need the LTS for these is debateable, and I may suppress tomorrow/d3 onwards so as I can do forecast vs actual comparisons, but LTS take up very little room so may not bother.

When did you make state_class changes @autoSteve ?

**Comment by BJReplay** [comment]
> where can I disable it?

@

**Comment by matomatusov** [comment]
Hi @BJReplay ,
thanks for the information on where to find it.
![no issue](https://github.com/user-attachments/assets/aeddc645-a72e-40de-bf1b-adb1117cdd35)

I see no problem there.

**Comment by BJReplay** [comment]
The original message **tells you how to fix** it - _and has a has a redirect in it_. It might take you to the original error - if it still exists.

I have seen this error myself when defining my own sensors and changing the UOM as a notification in HA: when I click on it, it offers me the opportunity to fix (update the old statistics to the current UOM) or ignore.

If you ignore, it clears the error, and you won't see it again.

**Comment by BJReplay** [comment]
Locked conversation to repo collabs.

This has become tar paper for unrelated discussions.

**Comment by autoSteve** [comment]
I can replicate this issue. But I cannot get to the root cause.

The sensor updates on forecast fetch or startup, and this is seen in the history, yet the sensor value shown is not correct, which makes no sense. Obscure HA bug?

I am going to switch that sensor to the per-five minute update interval and observe to see if it behaves.

**Comment by BJReplay** [comment]
> Obscure HA bug?

Yeah, I suspect.  I think it might be the same root cause as my laggy firing of events that fire seconds, or even minutes later than they should.  The update to update the value is stuck in a queue (and maybe gets discarded as aged by some cleanup process)?

**Comment by BJReplay** [comment]
Bed for me shortly.  Early start tomorrow.

**Comment by BJReplay** [comment]
202 downloads of 2.4.2 so far. 🤞

**Comment by autoSteve** [comment]
Talk about tar paper for unrelated this issue. Pot. Kettle. Black. Bwahaha!

(So living in the past that version. Pre-Oziee, I get what you mean. 😂 I almost did that myself earlier! Two-four-two-four-two... what?)

**Comment by autoSteve** [comment]
I have not observed this issue since switching the api_used counter listener to be five minute update.

**Comment by BJReplay** [comment]
I haven't seen it for a while, but I guess safe to close this with v4.2.5

**Comment by autoSteve** [comment]
I think I need to eat some humble pie regarding sensors not updating for used and last updated.

There was a glaring issue in the coordinator sensor update code, which has since been fixed.

To be honest, I am surprised these sensors were working before.
