### ISSUE TITLE
System health exception

### ISSUE THREAD

**Issue by autoSteve** [BJReplay/ha-solcast-solar#203]
### Discussed in https://github.com/BJReplay/ha-solcast-solar/discussions/185

<div type='discussions-op-text'>

<sup>Originally posted by **bert1111** October 17, 2024</sup>
Is this a solcast integration error or HA itself?
I see this in the logs after updating solarman integration and rebooting.
I am on the latest version of everything.

`Logger: homeassistant.components.system_health
Bron: components/system_health/__init__.py:89
integratie: Systeemstatus (documentatie, problemen)
Eerst voorgekomen: 15:10:03 (3 gebeurtenissen)
Laatst gelogd: 16:09:47

Error fetching info
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/system_health/__init__.py", line 89, in get_integration_info
    data = await registration.info_callback(hass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/system_health.py", line 27, in system_health_info
    used_requests = coordinator.solcast.get_api_used_count()
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'mappingproxy' object has no attribute 'solcast'`</div>

**Comment by autoSteve** [comment]
Continue here @bert1111.

**Comment by autoSteve** [comment]
To be honest, the system health return is currently _terrible_ @BJReplay, and of almost no use anyway. I am inclined to drop used requests and the rooftop sites count, leaving `can_reach` for the URL. This would avoid the exception entirely.

Additionally, the old way of looking at system health is no more in the current HA version that I can find. It was of some use back in 2019/2020, then I forgot all about it.

```
async def system_health_info(hass: HomeAssistant) -> dict[str, Any]:
    """Get info for the info page."""
    coordinator: SolcastUpdateCoordinator =list(hass.data[DOMAIN].values())[0]
    used_requests = coordinator.solcast.get_api_used_count()

    return {
        "can_reach_server": system_health.async_check_can_reach_url(hass, SOLCAST_URL),
        "used_requests": used_requests,
        "rooftop_site_count": len(coordinator.solcast.sites),
    }
```

**Comment by BJReplay** [comment]
My gut says HA glitch.

My early call is that we will get no useful information allowing repro.

Agreed on dropping rooftops.

Almost agreed on used requests. Only reason why not is that it is a bit of a 429 tell-tale if it all goes horribly wrong (10 retries fail) and debug logging isn't on.

**Comment by autoSteve** [comment]
Agree on the highly likely glitch.

> bit of a 429 tell-tale

Good point, but where can one see this information in the modern HA user interface or any diagnostic dump? Maybe I'm not looking hard enough... Get the API used from the sensor if needed. All of this info is included in the diagnostic dump, and this code seems a bit of a mostly-not-helpful relic.

Helpful would be a counter of the number of 429s hit for the past day, which should probably be in the diagnostic dump.

**Comment by BJReplay** [comment]
Agreed

**Comment by bert1111** [comment]
I can reproduce it by going to Repairs=> System information
![afbeelding](https://github.com/user-attachments/assets/90cac2f8-e013-406f-ba32-f1d7ac6b159b)

**Comment by BJReplay** [comment]
Thanks, @bert1111, that is helpful, so can I.

**Comment by autoSteve** [comment]
Reproduced as well.

It'll be gone in the next version, quite possibly replaced by something actually helpful... Thanks @bert1111.

**Comment by autoSteve** [comment]
It's useless, but at least it now works as is. This has been broken for a _very_ long time...

<img width="375" alt="image" src="https://github.com/user-attachments/assets/99e55509-f595-4972-a3d7-4488fb006654">

**Comment by autoSteve** [comment]
And it's wrong! 😂 "API requests remaining" is actually API requests used so far for the day. Lols. No one looks at this.

And more Urdu translations will be required to extend it. 🤦🏻

Why did I not just let you silently close that discussion BJ?

**Comment by BJReplay** [comment]
> Why did I not just let you silently close that discussion BJ?

🤷

I have **_relatively_** recently used system information when creating an issue on HA without it throwing that error (I think) - what was the fix?

Could a relatively recently made translation change have caused it?

**Comment by gcoan** [comment]
System Information is clearly a little used corner of HA.  Apart from various diagnostics from Home Assistant, Supervisor, Recorder, etc, the only non-HA components that show up in my System Information list are:

- HACS, arguably part of HA anyway
- AccuWeather, shows server connection and remaining allowed requests
- Solcast integration, broken as above

No other integrations or add-on's have bothered feeding it with data

**Comment by autoSteve** [comment]
(Python tute: Python dictionaries are inherently unordered, so when converted to a list you do not have a guaranteed order so you often sort with lambda on a dict key to ensure an order if that's what you need. The integration does this with forecast periods. What generally happens in reality is that the order that dict items are added tends to be retained in memory, unless adds/moves/changes so it often seems to work. I add the entry options before the coordinator gets instantiated, so entry options is almost always first-ish. Enter the almost always-ish exception.)

I know, @gcoan! (But there are some obscure ones out there that do.) Measuring 429s might be a fun project though.

Happy to be guided buy popular opinion. I honestly don't need more Urdu practice.

**Comment by BJReplay** [comment]
System Information may be little used, but is essential for raising issues on HA or any core integrations (as it is requested by the issue template).

That doesn't mean that we need to embrace it as a place to report data for our integration, but I have used it half a dozen times and I have only been using HA for six months!

**Comment by autoSteve** [comment]
Re-thinking: I am going to drop the 'requests remaining', 'rooftop sites' and abandon all thoughts of Urdu translations.

The current information is misleading, and no one looks at it.

Forget 429 counts. Hopefully we can solve for them, so it will be a non-issue. (_Warms up electric television..._)

I will leave the code stub that gets the coordinator. Someone may find it useful in future.

**Comment by BJReplay** [comment]
> Re-thinking

Hard Agree

As little as possible to fix is the right amount.

I'd consider pulling the entire system health hook but haven't yet read enough to know if that is good or bad.

Solcast Server reachable is not currently available anywhere else, but implicit in successful initial set up and forecast fetch.

Everything else is available elsewhere in diagnostics.

**Comment by autoSteve** [comment]
```
async def system_health_info(hass: HomeAssistant) -> dict[str, Any]:
    """Get info for the info page."""
    #for v in hass.data[DOMAIN].values():
    #    if isinstance(v, SolcastUpdateCoordinator):
    #        coordinator: SolcastUpdateCoordinator = v

    return {
        "can_reach_server": system_health.async_check_can_reach_url(hass, SOLCAST_URL),
    }
```

**Comment by autoSteve** [comment]
<img width="376" alt="image" src="https://github.com/user-attachments/assets/da283dd9-db1c-4ab8-ac9e-47978de66629">
