### ISSUE TITLE
Large number of errors in syslog every 5 minutes

### ISSUE THREAD

**Issue by tobiby** [BJReplay/ha-solcast-solar#227]
## Describe the bug

After installing and activating the current version v4.2.7. I got a large number of errors of the ha-solcast-solar integration every five minutes. Please see attached log.
I can also see that no values are being retrieved from solcast. All entities always remain empty.

## To Reproduce

1. Install the current version v4.2.7.
2. Add and configure ha-solcast-solar integration 

## Expected behavior

No errors in the syslog. Valid values for all the entities.

## Logs

I confirm:

- [x ] I have attached **debug** logs
[home-assistant.log](https://github.com/user-attachments/files/18053592/home-assistant.log)

- [ ] I have embedded **debug** logs in the issue description (enclosed in tick marks ``` for proper formatting)
- [ ] Confirmed **debug** logs are not required for this issue

Make sure you include logs from HA listing the output from the Solcast integration showing the error - this is particularly useful in debugging issues and helping to determine whether the issue is with the integration or the Solcast service

To add detailed debug information, add the following to your configuration.yaml and restart HA:

``` yaml
logger:
  default: warn
  logs:
    custom_components.solcast_solar: debug
```

To inspect and collect debug logs examine `/config/home-assistant.log` using File Editor or Visual Studio Code Server.

If you are using docker, it sometimes can be easier to gather logs using `docker compose logs -n 500 -f homeassistant` or similar

## Solcast Integration Version

- Integration Version 4.2.27

## Desktop (please complete the following information)

- OS: [e.g. iOS] Windows 11
- Browser [e.g. chrome, safari] Firefox
- Version [e.g. 22] 133.0

**Comment by autoSteve** [comment]
Great debug logs. Thanks.

This sequence fascinates:

1. Install the current version v4.2.7.
1. Add and configure ha-solcast-solar integration

Your log indicates that the files `solcast.json` and `solcast-undampened.json` exist on startup. What did you do to require a need to "add and configure ha-solcast-solar"?

With close to 4,000 downloads of v4.2.7 and no similar reports it is likely that you have done something out of the ordinary that I would like to understand. Clearly there is a "bug" somewhere, with that bug related to whatever it is that you did to require integration re-addition.

**Comment by autoSteve** [comment]
This is also a suspiciously short execution time to build the data structures for an existing installation:

> Task build_data took 0.001 seconds

I would also be interested to see a diagnostic dump from `Download diagnostics`, or alternatively the content of `solcast.json`.

<img width="349" alt="image" src="https://github.com/user-attachments/assets/f48d274f-b59d-4e90-a4b0-12cbad0fe36e">

**Comment by tobiby** [comment]
Thank you very much for the quick response.
After the hint with the solcast.json I removed the solcast integration and uninstalled solcast from Hacs.
Then I had to remove the solcast.json manually. I then reinstalled solcast and set up the integration again. 
Now everything seems to work. It looks like the error originates from an old solcast installation and could be solved by deleting solcast.json.

**Comment by autoSteve** [comment]
Good to hear, @tobiby.

It's a shame I didn't get my hands on `solcast.json` before you deleted it so I could get to the root cause. By doing so I might have been able to add a far more descriptive error, avoid an 'explosive' log, or even remedy the issue on startup.
