### ISSUE TITLE
Horizon instead of Damping

### ISSUE THREAD

**Issue by ximex** [BJReplay/ha-solcast-solar#230]
**Is your feature request related to a problem? Please describe.**
Instead of updating the damping values every day it would be much easier to set only values for the horizon. This only needs to get set once.

**Describe the solution you'd like**
I would suggest an input field to put in a comma separated values for the horizon. See Forecast Solar

**Additional context**
https://doc.forecast.solar/horizon
https://pypi.org/project/forecast-solar/

**Comment by autoSteve** [comment]
In my opinion, to apply dampening based on horizon data and sun position calculations is an interesting, but near impossible prospect.

I think it hard to pull off given we receive a combined direct and diffuse irradiation value for each interval from the Solcast API. I believe the way PVGIS works is that the local horizon data is provided to the PVGIS API and it adjusts the direct component then supplies the outcome. We don't have a mechanism to supply like data to the Solcast API.

Horizon shading mostly affects the direct component, and we do not have a direct/diffuse breakdown to adjust in the integration. The proportion of direct and diffuse at any given time with respect to an horizon model will also vary greatly making an assumed proportion useless. Example: A tall dense tree located close to a PV array shading mid-morning, vs. a neighbor's house up-slope of the current location shading late afternoon. These assumed proportions would need to be provided along with horizon data.

Happy to be contradicted.

**Comment by BJReplay** [comment]
> Instead of updating the damping values every day it would be much easier to set only values for the horizon. This only needs to get set once.

Yeah, nah.

I think what you want is the best of both worlds - you want the horizon-based forecasts from PVGIS, and the weather-based forecasts from Solcast.

What I'd suggest, if you want that, is to run both forecasts, and use the horizon-based forecasts to produce damping values by comparing them and using them to automatically produce damping for the Solcast forecasts.  Then you get the horizon-based shading reducing the cloud-based model that Solcast provides.

But as @autoSteve said, this seems like it is going much further than just setting up some damping factors - you don't have to adjust them each day.  Sure, sunrise / sunset times do change a little bit each day, but if you have a significant, unmoving horizon that shades your installation, the impact isn't that great that static damping isn't going to provide you with an adequate forecast for your needs.

The purpose of this integration is to provide free home users with adequate forecasts for home use; if you want accurate commercial forecasting, Solcast has a product for you :)

If you want super-accurate home forecasting for your own purposes, then utilise both sources, and use an approach such as that described in https://github.com/BJReplay/ha-solcast-solar/discussions/120 (specifically starting https://github.com/BJReplay/ha-solcast-solar/discussions/120#discussioncomment-10623338) by @Nilogax to automate damping changes.

**Comment by housemaister** [comment]
Would that be the "terrain_shading" feature of Solcast? (https://solcast.com/blog/whoa-terrain-shading-is-now-live-in-the-solcast-api)

**Comment by BJReplay** [comment]
Yeah, but not available on the free home subscription, which is why I said it has a product (implying paid).

Solcast also has the ability for paid services to feedback actual production (without terrain shading) so that it learns about degradation and other factors that impact production locally (e.g. a chimney, for example).

There's only so much work we (and that realistically means @autoSteve) is going to do re-creating paid features of a product in the free integration.

There's only so much accuracy people **need** at home.  If you need more, you need to be paying for it, or you don't need it.
