### ISSUE TITLE
Api calls limited to 10 even with an account that can still accept 50 calls

### ISSUE THREAD

**Issue by Gunth** [BJReplay/ha-solcast-solar#37]
**Describe the bug**
Since the latest update it seems that the number of api call is limited to 10 but i still have an account accepting 50 calls / days. I now have a warning saying that : "API limit exceeded, not getting forecast".

**Expected behavior**
No warning should be triggered for an account accepting 50 calls/ day until the 50 calls has been reach.

**Logs**

```
This error originated from a custom integration.

Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:771
integration: Solcast PV Forecast (documentation, issues)
First occurred: 09:06:00 (4 occurrences)
Last logged: 10:05:00

SOLCAST - API limit exceeded, not getting forecast
```

**Solcast Integration Version**
 - 4.0.29

**Comment by autoSteve** [comment]
Debug logs? Can't do anything with them, @Gunth...

When set for debug you see the limit returned from Solcast.

```
 logger:
   default: warn
   logs:
     custom_components.solcast_solar: debug
```

Reviewing logs is quite simple, but debug logs cannot be reviewed from the UI. The file ```/homeassistant/home-assistant.log``` must be viewed. I find the handiest way is to use the ```less``` command from the HAOS command line.

```less /homeassistant/home-assistant.log```
then...
```F``` key to follow live (capital F)
```/SOLCAST``` to search for and highlight lines containing "SOLCAST"
```Ctrl-C``` to exit follow mode
```PgUp```/```PgDn```/```Up```/```Down``` to hunt around.

**Comment by autoSteve** [comment]
An upgrade is available, by the way. It fixes a nasty little bug or two...

**Comment by autoSteve** [comment]
Thinking about this a bit more, I suspect that the call to Solcast to get the number of API calls has failed with a 429/too busy error after you upgraded to v4.0.29.

The integration now assumes ten calls as the default should the initial call fail.

Upgrade to v4.0.31, restart, and check whether a file called ```/homeassistant/solcast-usage.json``` has been created. This is a cache. Examine its contents, and verify that it now includes your limit of 50 calls.

**Comment by autoSteve** [comment]
To force a check for HACS updates, restart HA and wait a few minutes for the updates to appear...

**Comment by gcoan** [comment]
> To force a check for HACS updates, restart HA and wait a few minutes for the updates to appear...

You can also select the Solcast integration in HACS, click the three dots in the top corner and do 'update information' which causes HACS to check github for an update.  That's what I did

**Comment by Gunth** [comment]
After the upgrade to the 4.0.31 it's working correctly, i've the daily_limit to 50 in the solcast-usage.json.

Strange because I didn't see a 429 error with the previous version (4.0.29) that could cause the API call count to fail, anyway it's not working correctly on each ha restart.

Thanks !!
