### ISSUE TITLE
unexpected keyword argument 

### ISSUE THREAD

**Issue by Markyt77** [BJReplay/ha-solcast-solar#40]
### The problem

Had to restart HA today which broke my exsiting Oziee install. I've added this repor to HACS but it's refusing to start' Front end reports 'Failed to set up', logs report TypeError: ConfigEntries.async_update_entry() got an unexpected keyword argument 'version' 

I've deleted from HA and reinstalled, generated a new API key, restarted and refreshed, still can't get Solcast up and running again.

### What version of Solcast Integration has the issue?

4.0.31

### What version of Home Assistant are you using?

2024.2.1

### Logs debug/info/error output

```txt
2024-06-17 11:22:26.200 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Solcast Solar for solcast_solar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 444, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/solcast_solar/__init__.py", line 76, in async_setup_entry
    hass.config_entries.async_update_entry(entry, options=new, version=7)
TypeError: ConfigEntries.async_update_entry() got an unexpected keyword argument 'version'
```

**Comment by BJReplay** [comment]
At first glance it looks like we have discovered that you are running a version of homeassistant that is not compatible with this integration.

Is there a reason why you are running this version of homeassistant which is now quite old?

**Comment by Markyt77** [comment]
Thanks for the quick reply! I get HA so everything is stable (it has a lot of integrations) and leave it to do it's thing as breaking changes in upgrades give me wrinkles. I'll upgrade everything now and retry.

**Comment by autoSteve** [comment]
This really interests me, @BJReplay and @Markyt77 (cc: @kernow from discussion). This relates to changes that were part of oziee's missing 4.0.23 changes...

What version are you on @kernow?

**Comment by Markyt77** [comment]
You were right, updating HA to latest has resovled my issue, thanks again for the quick reply!

**Comment by autoSteve** [comment]
That still begs the question, why did oziee introduce a breaking change?

**Comment by BJReplay** [comment]
> and leave it to do it's thing as breaking changes in upgrades give me wrinkles
Fair enough! 

Only 3.17% are on 2024.2.

I am only guessing that await component.async_setup_entry is breaking for 2024.2 - that wouldn't be a surprise - other async methods were introduced in 2024.6 so perhaps async_setup_entry was introduced after 2024.2

**Comment by BJReplay** [comment]
P. S. Thanks for the detailed issue with logging!

**Comment by Markyt77** [comment]
> That still begs the question, why did oziee introduce a breaking change?

I meant breaking changes in general, I've got HA doing a lot of jobs and updates to various integrations often bring in breaking changes, not related to Solcast in this instance

**Comment by BJReplay** [comment]
> That still begs the question, why did oziee introduce a breaking change?

I guess he didn't realise at the time?

**Comment by autoSteve** [comment]
The root of this is because "version=" is not recognised as a kwarg for async_update_entry(). That _has_ to be new then, and very recent, so why change until HA say "we're going to remove what you were doing as a breaking change? Or at very least try:/except: for it???

Gah.

I love this integration.

**Comment by kernow** [comment]
I am on version 2024.2.5, so not too old as I upgraded a few months back. I've not updated to the latest version as I believe there was an issue with some other integration I'm using so was holding off upgrading for a bit.

**Comment by BJReplay** [comment]
That is the problem, unfortunately. That version doesn't support the way we use async_setup_entry - which we didn't realise until this issue was opened.

**Comment by BJReplay** [comment]
> I am going to try and craft a work-around for this

Should we bite the bullet and make 2024.5 the minimum ha version to avoid that?

**Comment by autoSteve** [comment]
Love it. Send it @kernow.

Or check out ```__init.py__``` at https://github.com/BJReplay/ha-solcast-solar/commit/da1baa596c2a570f74d1af7ef5e18e78c921129a

Or not now that you've upgraded and all is working now.

I'm gonna need to downgrade mine to test it to stop other folks smacking their face into this rake handle.

Honestly, if I ruled the world...

**Comment by autoSteve** [comment]
```ha core downgrade --version 2024.2.1```

Result:

Checks out just fine. I'll create a PR. Don't bother creating a new release for this, @BJReplay. Wait until the next 429 issue... 🤣
