### ISSUE TITLE
Wierd readings on the solar production bar chart

### ISSUE THREAD

**Issue by RILEYBATES** [BJReplay/ha-solcast-solar#50]
### The problem

There are brown bars signifying something on the solar production forecasts.  Seems to relate to the solcast integration.

![Screenshot_20240622_072632_Home Assistant](https://github.com/BJReplay/ha-solcast-solar/assets/155683877/7a4d0a18-5412-4311-8270-74352545387c)

![Screenshot_20240622_072649_Home Assistant](https://github.com/BJReplay/ha-solcast-solar/assets/155683877/d8bf5b28-c9a1-4300-b375-0aeeb2f6398a)

![Screenshot_20240622_072710_Home Assistant](https://github.com/BJReplay/ha-solcast-solar/assets/155683877/3d34f35b-2421-42ad-afab-1cdaf2c528e2)

### What version of Solcast Integration has the issue?

V4.0.31

### Logs debug/info/error output

```txt
No error message just error in chart
```

**Comment by autoSteve** [comment]
Looks like a case of weird config, and you're going to get a weird outcome.

<img width="954" alt="image" src="https://github.com/BJReplay/ha-solcast-solar/assets/37229860/1d2b3368-23fb-4f5d-8c59-f93374d3abb1">

I have the solar sensor getting production from my Powerwall...

<img width="448" alt="image" src="https://github.com/BJReplay/ha-solcast-solar/assets/37229860/b31a50c9-9274-48b3-bfff-934b25d56383">

**Comment by RILEYBATES** [comment]
OK, be happy if the config was incorrect but what's wierd?  This was working and I haven't changed anything other than updating the integration...

**Comment by autoSteve** [comment]
The sensor you have specified to measure solar production is measuring FORECASTED prouction today. Of COURSE that is going to introduce weirdness.

That sensor has to be for ACTUAL solar production.

I take it you have one solar production config for GivTCP, and have created a second one for Solcast. I have one, and that single one has the forecast option enabled for Solcast.

<img width="517" alt="image" src="https://github.com/BJReplay/ha-solcast-solar/assets/37229860/a43505c7-456e-474a-bd30-45ab1c224a7d">

Show me that the config of the GivTCP has the option to enable forecast via Solcast.

I'm hovering over the close issue button...

**Comment by autoSteve** [comment]
Out of interest, do you still have long-term forecast detail shown in the energy dashboard after upgrading to 4.0.31? Like go to a month view and check this month and last month to see if the forecast history is still there...

**Comment by RILEYBATES** [comment]
Oh ok, I'll have a look and see what I can find in the GivTCP setup.  It's always been set up this way, been using this integration (originally from Oozie now switched to yours) for quite a while now and never saw these bars.  But let me see if I can find something in the GivTCP setup.

By the way, this integration saved me as I lost all this when Oozie deleted his account so kudos for keeping yours going.. I'm certainly not having a go at it just wondered if I was doing something wrong.

Please feel free to close was just looking for some advice

**Comment by autoSteve** [comment]
It interests me that no config changed and it didn't do this with Oziee's.

We may have inadvertantly fixed something that might be causing another issue that I'm chasing, so out of interest, do you still have long-term forecast detail shown in the energy dashboard after upgrading to 4.0.31? Like go to a month view and check this month and last month to see if the forecast history is still there...

**Comment by autoSteve** [comment]
(And do that before changing any existing config, please.)

**Comment by RILEYBATES** [comment]
I don't think so. This is what I can see on the month view.  Not sure if I don't have any forecast prior to last week though because I switched to your repository?


[Image]



Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by autoSteve** [comment]
Umm. can't see any image.

<img width="433" alt="image" src="https://github.com/BJReplay/ha-solcast-solar/assets/37229860/ecde2fb5-c4ce-42f5-a292-a213ae4265f5">

**Comment by RILEYBATES** [comment]
By the way don't know if it helps but I seem to get the bars either at the start of a new day or when I poll new information but not in between

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by autoSteve** [comment]
> I seem to get the bars either at the start of a new day or when I poll

Makes sense. This sensor gets its value from a variable called 'tally', which is updated midnight/forecast get.

**Comment by RILEYBATES** [comment]
Sorry I replied on the email it didn't seem to send the image...

![Screenshot_20240622_080723_Home Assistant](https://github.com/BJReplay/ha-solcast-solar/assets/155683877/5e65bd72-75ce-411a-a45c-ccdb5f79f439)

**Comment by autoSteve** [comment]
Yep. That's the issue. Thanks for looking and providing another data point.

At this stage I don't know whether the history has been purged, or whether it is just not showing.

Thanks. Now fix your config!
