### ISSUE TITLE
Zero values for estimates

### ISSUE THREAD

**Issue by chicagoandy** [BJReplay/ha-solcast-solar#59]
### The problem

I am consistently getting zero values for all forcast fields.    The 'Power' fields have data.

### What version of Solcast Integration has the issue?

v4.0.31

### What version of Home Assistant are you using?

core-2024.6.4

### Diagnostics information

[config_entry-solcast_solar-60744a9684c0dfc2f346ff3b902be1b2.json](https://github.com/user-attachments/files/15975598/config_entry-solcast_solar-60744a9684c0dfc2f346ff3b902be1b2.json)

### Logs debug/info/error output

```txt
2024-06-25 13:42:52.410 DEBUG (MainThread) [custom_components.solcast_solar] Solcast Migrating from version 7
2024-06-25 13:42:52.410 DEBUG (MainThread) [custom_components.solcast_solar] Solcast Migration to version 7 successful
2024-06-25 13:42:52.413 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST apiCacheEnabled=False, solcast-sites.json=True
2024-06-25 13:42:52.413 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - connecting to - https://api.solcast.com.au/rooftop_sites?format=json&api_key=REDACTED
2024-06-25 13:42:52.688 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data code http_session returned data type is <class 'dict'>
2024-06-25 13:42:52.688 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data code http_session returned status 200
2024-06-25 13:42:52.688 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - writing sites data cache
2024-06-25 13:42:52.689 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - sites_data: {'sites': [{'name': 'Home', 'resource_id': '664e-4f3b-37a3-12a4', 'capacity': 15, 'capacity_dc': 7, 'longitude': -**.******, 'latitude': **.******, 'azimuth': -172, 'tilt': 40, 'install_date': '2024-06-07T04:00:00.0000000Z', 'loss_factor': 0.9, 'tags': []}, {'name': 'west', 'resource_id': '94bc-c144-6013-8c52', 'capacity': 15, 'capacity_dc': 3.3, 'longitude': -**.*****, 'latitude': **.******, 'azimuth': 84, 'tilt': 40, 'install_date': '2024-06-07T04:00:00.0000000Z', 'loss_factor': 0.9, 'tags': []}], 'page_count': 1, 'current_page': 1, 'total_records': 2}
2024-06-25 13:42:52.689 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - getting API limit and usage from solcast
2024-06-25 13:42:53.096 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - writing usage cache
2024-06-25 13:42:53.097 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - API counter is 3/10
2024-06-25 13:42:53.100 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - load_saved_data file exists.. file type is <class 'dict'>
2024-06-25 13:42:53.107 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-25 contains only 0 of 48 records and may produce inaccurate forecast data
2024-06-25 13:42:53.107 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-26 contains only 0 of 48 records and may produce inaccurate forecast data
2024-06-25 13:42:53.107 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-27 contains only 0 of 48 records and may produce inaccurate forecast data
2024-06-25 13:42:53.108 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-28 contains only 0 of 48 records and may produce inaccurate forecast data
2024-06-25 13:42:53.108 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-29 contains only 0 of 48 records and may produce inaccurate forecast data
2024-06-25 13:42:53.108 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] SOLCAST - Data for 2024-06-30 contains only 0 of 48 records and may produce inaccurate forecast data
2024-06-25 13:42:53.111 INFO (MainThread) [custom_components.solcast_solar] Solcast Integration version number: v4.0.31
2024-06-25 13:42:53.111 DEBUG (MainThread) [custom_components.solcast_solar.coordinator] Finished fetching solcast_solar data in 0.000 seconds (success: True)
2024-06-25 13:42:53.124 INFO (MainThread) [custom_components.solcast_solar] SOLCAST - Solcast API data UTC times are converted to America/New_York
```

### Additional information

I am able to view forecasts with data via: https://api.solcast.com.au/rooftop_sites/SITE_KEY/forecasts

**Comment by autoSteve** [comment]
(Removed your lat/longitude from log.)

The integration looks to be working correctly, it's just that Solcast are not sending values to you. Here's the answer: ```0 of 48 records and may produce inaccurate forecast data```. Most inaccurate, I'd say.

Here's what a healthy return from Solcast should yield:

```
SOLCAST - Data for 2024-06-25 contains all 48 records
SOLCAST - Data for 2024-06-26 contains all 48 records
SOLCAST - Data for 2024-06-27 contains all 48 records
SOLCAST - Data for 2024-06-28 contains all 48 records
SOLCAST - Data for 2024-06-29 contains all 48 records
SOLCAST - Data for 2024-06-30 contains all 48 records
SOLCAST - Data for 2024-07-01 contains all 48 records
SOLCAST - Data for 2024-07-02 contains all 48 records
```

Has this ever worked?

Your 'Capacity AC' and 'Capacity DC' settings in solcast for each rooftop look interestingly wrong. DC generation capability should exceed AC generation in kW. What do you see at solcast.com for the forecast projection graphs for each rooftop site? Are they flat lines?

**Comment by autoSteve** [comment]
Looking at the diagnostics file I see that there appear to be forecasted values for PV generation for the average values. 'estimate10' and 'estimate90' are all zero from Solcast. What's the setting of the select ```Solcast PV Forecast Use Forecast Field```? ```estimate```, ```estimate10``` or ```estimate90```?

**Comment by Batfinkus** [comment]
I'm having the same issue, don't know if I'm looking in the right place, but when I pull down the CSV record from solecast, there's figures on most of it, but glaring gaps of zero's as well, so is it solecist not sending, or a settings issue? I haven't changed anything and this only started yesterday

[GetRooftopSiteForecast.csv](https://github.com/user-attachments/files/15985909/GetRooftopSiteForecast.csv)

**Comment by autoSteve** [comment]
@Batfinkus, integration version? 4.0.31, or one of the new pre-repeases? Which forecast is used? forecast/forecast10/forecast90?

The zeros in the CSV will be when the sun don't shine... It's UTC times.

I would like to see your debug log to see whether the same 0/48 thing is going on.

**Comment by Batfinkus** [comment]
Integration version v4.0.31

Ive attached the debug log hopefully that helps!

[config_entry-solcast_solar-833349a46dd33fbc6ac7f62335f9f41c-2.json](https://github.com/user-attachments/files/15986100/config_entry-solcast_solar-833349a46dd33fbc6ac7f62335f9f41c-2.json)

Just noticed (that I should have noticed before) the last posted date was 19th June, reloading the integration doesn't seem to force an update, it stays at that date

**Comment by autoSteve** [comment]
Interesting. It looks like the forecast data is there.

> the last posted date was 19th June

Noticed where?

```"last_updated": "2024-06-19T09:11:56.527149+00:00",```

Isn't that when you updated to 4.0.31, Zulu time?

I'd be interested to see what enabling debug logging does, looking at ```less /homeassistant/home-assistant.log``` after following post 2 at https://github.com/BJReplay/ha-solcast-solar/discussions/38.

I'd also be very interested to hear what happens if you run v4.0.33 (which is a pre-release, so you need to enable betas in HACS download). Much has been done recently by @isorin on the forecast processing front, mostly with an eye on performance.

An integration restart will not force a forecast update. It is designed that way, and rather the data is read from a cache of last forecast data. Forecasts are only updated when they are requested manually or by an automation.

**Comment by autoSteve** [comment]
```last_updated": "2024-06-19T09:11:56.527149+00:00```

Nope. That's the time the forecast was last updated...

I _really_ need to see what's going on in the debug level ```/homeassistant/home-assistant.log```...

**Comment by autoSteve** [comment]
@chicagoandy, you also have a ```last_updated``` date in the past. 17th June...

**Comment by Batfinkus** [comment]
> `last_updated": "2024-06-19T09:11:56.527149+00:00`
> 
> Nope. That's the time the forecast was last updated...
> 
> I _really_ need to see what's going on in the debug level `/homeassistant/home-assistant.log`...

[home-assistant.log](https://github.com/user-attachments/files/15986553/home-assistant.log)

Ive removed my lat/long from it , I had already enabled debug earlier on today just in case something jumped out at my skill level, as opposed to well above my skill level where we are now!

**Comment by autoSteve** [comment]
Auto redaction of lat/long coming soon...

Looking at the code this means that ```http_data_call()``` is not returning True. That is the only way that the variable ```last_updated``` could not be updated. Hmmm.

```
        failure = False
        for site in self._sites:
            _LOGGER.debug(f"SOLCAST - API polling for rooftop {site['resource_id']}")
            #site=site['resource_id'], apikey=site['apikey'],
            usageCacheFileName = self.get_api_usage_cache_filename(len(self._sites), site['apikey'])
            result = await self.http_data_call(usageCacheFileName, site['resource_id'], site['apikey'], dopast)
            if not result:
                failure = True

        self._data["version"] = _JSON_VERSION
        if not failure:
            self._data["last_updated"] = dt.now(timezone.utc).isoformat()
            self._loaded_data = True
```

**Comment by chicagoandy** [comment]
Indeed Solcast is reporting 0 API calls today.

I do see my two SITEs reporting properly in the Solcast UI.
![image](https://github.com/BJReplay/ha-solcast-solar/assets/81330040/f2b1d9dd-b67a-44af-ab2b-277c9cbf18b4)

I've updated to Beta 4.33 and have the same results.    Log & Diagnostics attached.   (long/lat redacted)
[4-33-home-assistant_solcast_solar_2024-06-26T13-40-47.918Z.log](https://github.com/user-attachments/files/15989329/4-33-home-assistant_solcast_solar_2024-06-26T13-40-47.918Z.log)
[config_entry-solcast_solar-2319840c10d3b014a6654ba7c8632675.json](https://github.com/user-attachments/files/15989330/config_entry-solcast_solar-2319840c10d3b014a6654ba7c8632675.json)

**Comment by autoSteve** [comment]
Thanks for trying the beta, @chicagoandy. It's good code, and I've been running it for quite a while with zero issue.

There's really not much to go on in that debug log. It just shows a startup with load of prior cached forecast data. My suspicion is that your automation is not asking the Solcast integration for updates for some reason, or the automation isn't listening to the request, so asking it manually would rule in or out that the integration is the issue, and maybe indicate where the problem is.

Could you manually trigger a Solcast update and re-post a debug log of the things that happen at the time? Developer tools | Services | Solcast PV Forecast: Update.

<img width="1217" alt="image" src="https://github.com/BJReplay/ha-solcast-solar/assets/37229860/2bb18025-cdc5-42d9-95f5-1088f244d519">

**Comment by autoSteve** [comment]
@Batfinkus, your log looks like repeated restarts of the integration hoping that something will come good. Could you also please manually trigger a forecast? Developer tools | Services | Solcast PV Forecast: Update. Nothing new will happen by just restarting the integration. Absolutely nothing from a get forecast POV.

The integration will just use cached data on restart. It is designed to do so, primarily so it does not needlessly chew up precious daily API calls. For details, see ```Q: What polls to Solcast happen, when do they happen, and are they important?``` in https://github.com/BJReplay/ha-solcast-solar/discussions/38.

A forecast update call must occur.

Have you checked that your automation is firing? Check its last run time.

**Comment by Batfinkus** [comment]
> @Batfinkus, your log looks like repeated restarts of the integration hoping that something will come good. Could you also please manually trigger a forecast? Developer tools | Services | Solcast PV Forecast: Update. Nothing new will happen by just restarting the integration. Absolutely nothing from a get forecast POV.
> 
> The integration will just use cached data on restart. It is designed to do so, primarily so it does not needlessly chew up precious daily API calls. For details, see `Q: What polls to Solcast happen, when do they happen, and are they important?` in #38.
> 
> A forecast update call must occur.
> 
> Have you checked that your automation is firing? Check its last run time.

It was repeated restarts, I hadn't realised that it would only call when required, but at least I now know how to call it!

That seems to have kicked it into gear and I have figures now, I did change a few times between estimate10 and estimate90 after it reloaded.

Which automation do you mean (apologies!)

[Uploading config_entry-solcast_solar-833349a46dd33fbc6ac7f62335f9f41c.json…]()

**Comment by autoSteve** [comment]
Changing between ```estimate```, ```estimate10``` and ```estimate90``` will cause an automation reload under the covers. It needs to. Don't ask. It's on the to-do list to think about.

The ```README.md``` holds many secrets. Dark secrets that only the desperate seek...

https://github.com/BJReplay/ha-solcast-solar

Secrets like... this one, which is an automation that will optimise Solcast forecast gets throughout daylight hours. But the choice is yours. Call it whenever you want, up to your API call limit. We don't judge. But an HA automation that does what it needs to do is essential. (Please read the README.md. For this, and two rooftop sites the number of API calls needs to be halved.)

Oziee did away with an internal integration mechanism to fire a forecast get periodically, because soooo. many. problems. So it was dead to him, and removed. And I'm with him. This is to individual taste, circumstance, and API limit.

Sure, it's not a next, next, next, finish M$ install, but you have control, which I like.

```yaml
alias: Solcast update
description: ""
trigger:
  - platform: template
    value_template: >-
      {% set nr = as_datetime(state_attr('sun.sun','next_rising')) | as_local %}
      {% set ns = as_datetime(state_attr('sun.sun','next_setting')) | as_local %}
      {% set api_request_limit = 10 %}
      {% if nr > ns %}
        {% set nr = nr - timedelta(hours = 24) %} 
      {% endif %}
      {% set hours_difference = (ns - nr) %}
      {% set interval_hours = hours_difference / api_request_limit %}
      {% set ns = namespace(match = false) %}
      {% for i in range(api_request_limit) %}
        {% set start_time = nr + (i * interval_hours) %}
        {% if ((start_time - timedelta(seconds=30)) <= now()) and (now() <= (start_time + timedelta(seconds=30))) %}
          {% set ns.match = true %}
        {% endif %}
      {% endfor %}
      {{ ns.match }}
condition:
  - condition: sun
    before: sunset
    after: sunrise
action:
  - delay:
      seconds: "{{ range(30, 360)|random|int }}"
  - service: solcast_solar.update_forecasts
    data: {}
mode: single
```

**Comment by chicagoandy** [comment]
<sigh>
I'm sorry.   I was using the wrong service-call to update.   Calling one of the queries instead of update_forecasts.

Thanks for the automation, looks great.

**Comment by Batfinkus** [comment]
yep, I'll take the hit on that one for not reading the manual, apologies!  Our solar has been down for the last 2 months as we were getting a new roof put on, so I didn't really look at this, except to update to the new repository and reinstall when the panels went back up!

**Comment by autoSteve** [comment]
Calling this one closed. The very best with embracing @BJReplay's Solcast integration, @chicagoandy & @Batfinkus. You'll love it, and love the journey to even better in the future. 😘
