### ISSUE TITLE
Versions Deployed

### ISSUE THREAD

**Issue by Blackduke77** [BJReplay/ha-solcast-solar#79]
**Describe the bug**
Fresh install from HCAS, doesn't seem to install the latest

**To Reproduce**
1. remove previous version
2. Delete old repository
3. Add BJReplay repository 
4. add integration
5. Version 4.0.26 installed

**Expected behaviour**
Version 4.0.31 should be deployed

**Screenshots**
![image](https://github.com/BJReplay/ha-solcast-solar/assets/8461433/f5277aa4-1e75-4e20-bc1c-fd452a75b469)

**Additional context**
Manually downloading files from github and copying them onto HA, the version updates to 4.0.37

**Comment by Blackduke77** [comment]
Thanks for the prompt reply, I just been reading some of your notes on this, thanks for keeping this going, sounds like PR for HCAS etc is still in progress, so I jumped the gun

**Comment by autoSteve** [comment]
Indeed it is. Three reviews done, and just a final merge from a maintainer to go until 🎉😌.

**Comment by autoSteve** [comment]
Feel free to jump into the v4.0.37 pre-release discussion topic, @Blackduke77. And welcome aboard.

https://github.com/BJReplay/ha-solcast-solar/discussions/77

Ay positive or negative feedback is welcome.
