### ISSUE TITLE
Fix My Home assistant button

### ISSUE THREAD

**Issue by cromefire** [BJReplay/ha-solcast-solar#8]
**Describe the bug**
The my home assistant button in the readme registers the repository as `plugin` which seems to register it as Lovelace widget.

**To Reproduce**
1. Click on the my home assistant button
2. Follow the instructions on screen
3. You will find the integration in the Lovelace widgets

**Expected behavior**
The repository is added under integratons

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7 Pro
 - OS: Android 14
 - Browser: HA App
 - Version: Latest from play store

**Additional context**
You probably only have to change the type in the URL to `integration`

**Comment by mZ738** [comment]
Created a [PR](https://github.com/BJReplay/ha-solcast-solar/pull/11)

Should Work with this Link.
 https://my.home-assistant.io/redirect/hacs_repository/?owner=BJReplay&repository=ha-solcast-solar&category=integration.
