### ISSUE TITLE
No data from Solcast:  No such file or directory

### ISSUE THREAD

**Issue by Unlik** [BJReplay/ha-solcast-solar#98]
**The problem**
Because the same issue  (https://github.com/BJReplay/ha-solcast-solar/issues/92) occurred I upgraded to beta V.4.0.39, then got other errors in the log. I am running HA Core 2024.3.3 with HACS in Debian. Prior Solcast integration from oziee worked normally.

**What version of Solcast Integration has the issue?**
V.4.0.39 Beta

**Logs debug/info/error output**
```
Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:294
integration: Solcast PV Forecast (documentation, issues)

Exception in sites_data(): Traceback (most recent call last): File "/home/xxxxx/.homeassistant/custom_components/solcast_solar/solcastapi.py", line 221, in sites_data async with aiofiles.open(apiCacheFileName, 'w') as f: File "/home/xxxxx/homeassistant/lib/python3.11/site-packages/aiofiles/base.py", line 63, in __aenter__ return await self ^^^^^^^^^^ File "/home/xxxxx/homeassistant/lib/python3.11/site-packages/aiofiles/base.py", line 59, in __await__ self._obj = yield from self._coro.__await__() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xxxxx/homeassistant/lib/python3.11/site-packages/aiofiles/threadpool/__init__.py", line 92, in _open f = await loop.run_in_executor(executor, cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: '/config/solcast-sites.json'
```
```
Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:163
integration: Solcast PV Forecast (documentation, issues)

Exception in write_api_usage_cache_file(): [Errno 2] No such file or directory: '/config/solcast-usage.json'
```
```
Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:164
integration: Solcast PV Forecast (documentation, issues)

Traceback (most recent call last): File "/home/xxxxx/.homeassistant/custom_components/solcast_solar/solcastapi.py", line 160, in write_api_usage_cache_file async with aiofiles.open(json_file, 'w') as f: File "/home/xxxxx/homeassistant/lib/python3.11/site-packages/aiofiles/base.py", line 63, in __aenter__ return await self ^^^^^^^^^^ File "/home/xxxxx/homeassistant/lib/python3.11/site-packages/aiofiles/base.py", line 59, in __await__ self._obj = yield from self._coro.__await__() ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xxxxx/homeassistant/lib/python3.11/site-packages/aiofiles/threadpool/__init__.py", line 92, in _open f = await loop.run_in_executor(executor, cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: '/config/solcast-usage.json'
```
```
Logger: custom_components.solcast_solar.solcastapi
Source: custom_components/solcast_solar/solcastapi.py:454
integration: Solcast PV Forecast (documentation, issues)

Solcast site count is zero in load_saved_data(); the get sites must have failed, and there is no sites cache
```
Is there anything else I may do?

**Comment by autoSteve** [comment]
More specifics about your environment, please?

I am thinking there is no `/config` directory in your set up, so where are your HA configuration files stored?

**Comment by autoSteve** [comment]
This: `/home/xxxxx/.homeassistant/custom_components/solcast_solar`.

I think that your Home Assistant configuration is in `/home/xxxxx/.homeassistant`, @Unlik. This will break the integration, because it expects a different directory layout.

For a quick fix, create a symbolic link to this directory, target as `/config`. Restart. (`ln -s /home/xxxxx/.homeassistant /config`)

Or wait for v4.0.40, where I have solved this for your corner case.

**Comment by autoSteve** [comment]
Brilliant info. I will consider the fix further to ensure it still covers Docker installs, which had previously been broken.

I've been HAOS from day one, so sadly did not consider this.

**Comment by autoSteve** [comment]
v4.0.40 is released.

**Comment by Unlik** [comment]
Hello @autoSteve, may I somehow affect the settings for config folder? From log I still can see:
`2024-07-26 07:53:41.215 DEBUG (MainThread) [custom_components.solcast_solar.solcastapi] Configuration directory is /config`
 So the version 4.0.40 does not help with folder issue.

**Comment by autoSteve** [comment]
I can see why this is.

Unfortunately the config folder is still hard coded (I found another reference in `__init__.py`. To get you going for now, edit this file, find `/config` at line 125, and you can change it to suit your system.

I need to detect which folder a given deployment type of HACS is using, because if I change it back to not feature a hard coded `/config` then Docker installs will fail. 🤦🏻

It is my understanding that custom components are always installed in subdirectories under the config folder, so what I think will fix this is to determine the running location of the `__init__` script, which will be `[config]/custom_components/solcast_solar`, and then build a path as two levels higher. Hopefully Docker installs are structured the same. (Do you know, @BJReplay?)

I'll give coding this a go, which won't be hard or take too long, then will hit you up to test it.

**Comment by Unlik** [comment]
FYI: it somehow works if I manually set up the path with the solcast.json file in the` solcastapi.py:115`. The new issue is about the remaining today's forecast which is bigger than just the total today's forecast. Shall I open a new issue?

**Comment by Unlik** [comment]
48.32 vs 48.37 kW. I am not sure whether it is related:
```
Traceback (most recent call last): File "/home/xxxxx/.homeassistant/custom_components/solcast_solar/solcastapi.py", line 835, in get_max_forecast_pv_estimate _data = self._data_forecasts if site is None else self._site_data_forecasts[site] ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^ KeyError
```
and
```
Traceback (most recent call last): File "/home/xxxxx/.homeassistant/custom_components/solcast_solar/solcastapi.py", line 820, in get_forecast_pv_moment res = pchip((time_utc - interval_start).total_seconds(), st_i) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/xxxxx/.homeassistant/custom_components/solcast_solar/solcastapi.py", line 813, in pchip _data[i][_data_field], ~~~~~^^^ IndexError: list index out of range
Traceback (most recent call last): File "/home/xxxxx/.homeassistant/custom_components/solcast_solar/solcastapi.py", line 805, in get_forecast_pv_moment _data = self._data_forecasts if site is None else self._site_data_forecasts[site] ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^ KeyError
```

**Comment by autoSteve** [comment]
The `KeyError` at `self._site_data_forecasts[site]` is odd, possibly indicating a forecast fetch issue.

The `list index out of range` also possibly indicates a forecast fetch issue.

This is just guessing without seeing a complete debug log of what the forecast get data contains.

The difference in forecast remaining and forecast today is being introduced by the addition of some recent interpolation of the forecast data using a cubic spline. This likely wants tweaking, but is not worth opening a separate issue. I already know about it, and the difference is so minor that it just forms an annoyance.

**Comment by autoSteve** [comment]
In `__init.py__` at line 6, add

```
import os
```

At the new line 123 add the new variable `configDir` and edit the dict `hass.config.path`...

```
    configDir = os.path.abspath(os.path.join(__file__ ,"../../.."))
    options = ConnectionOptions(
        entry.options[CONF_API_KEY],
        SOLCAST_URL,
        hass.config.path('%s/solcast.json' % configDir),
```

**Comment by Unlik** [comment]
After these changes it is probably working properly - as I am out of API limit today I will be back tomorrow with fresh report.

**Comment by BJReplay** [comment]
> Hopefully Docker installs are structured the same. (Do you know, @BJReplay?)

As far as I know, but, I don't actually know - but I do know that I have a default installation and can have a look around as I did find out a lot more than I would like to know when I had to remove the oziee integration manually to get HA to start a couple of months ago, so am somewhat familiar with a bunch of HA Docker config files.

Is the question "where is the default location of the config folder?" or is the question "is the default installation location custom_components/component_name and is it always under the config folder?"

**Comment by autoSteve** [comment]
@BJReplay, the question is, "Is the default installation location custom_components/component_name and is it always under the config folder?"

The code I propose gets the folder location that the Solcast integration runs at, and then assumes that "two levels up" is the config folder location. Seems sane to me.

@Unlik, did that change work?

**Comment by Unlik** [comment]
It's working perfectly for me now, thank you for the correction!

**Comment by BJReplay** [comment]
> The code I propose gets the folder location that the Solcast integration runs at, and then assumes that "two levels up" is the config folder location. Seems sane to me.

I can't see anywhere that names the config folder under a docker install.

The config folder is mounted in the docker definition, so should always be called config within the Docker VM.

```
     homeassistant:
         container_name: homeassistant
         image: ghcr.io/home-assistant/home-assistant:latest
         volumes:
             - ./ha:/config
             - /etc/localtime:/etc/localtime:ro
             - /run/dbus:/run/dbus:ro
         restart: unless-stopped
         ports:
             - target: 8123
               published: 8123
               mode: host

```
On the host, it looks like this:

```
~/ha$find . -mindepth 1 -maxdepth 2 -type d
./.storage
./backups
./custom_components
./custom_components/epa_victoria_air_quality
./custom_components/opennem
./custom_components/import_statistics
./custom_components/o365
./custom_components/bureau_of_meteorology
./custom_components/hacs
./custom_components/solcast_solar
./custom_components/spook
./custom_components/localtuya
./custom_components/blitzortung
./blueprints
./blueprints/script
./blueprints/automation
./deps
./www
./www/community
./tts
./.cloud
```

**Comment by BJReplay** [comment]
Adding, for docker, the instructions specifically note: https://www.home-assistant.io/installation/alternative#install-home-assistant-container

Adjust the following Terminal command as follows :

`sudo docker run --restart always -d --name homeassistant -v /PATH_TO_YOUR_CONFIG:/config --device=/PATH_TO_YOUR_USB_STICK -e TZ=Australia/Melbourne --net=host ghcr.io/home-assistant/home-assistant:stable`

Replace /PATH_TO_YOUR_CONFIG points at the folder where you want to store your configuration - **make sure that you keep the :/config part**

It's clear that docker installs expect the root config path to be mapped as config.
